name: lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache multiple paths
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            $RUNNER_TOOL_CACHE/Python/*
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-build-${{ matrix.python-version }}
      - name: install-reqs
        run: python -m pip install --upgrade mypy typing-extensions ruff
      - name: run mypy
        run: cd spec/API_specification && mypy dataframe_api && mypy examples
      - name: run ruff format
        run: cd spec/API_specification && ruff format dataframe_api examples --diff
      - name: run ruff check
        run: cd spec/API_specification && ruff check dataframe_api examples --no-fix
